/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HistorialPedidosCompletados;

import ProcesarPedidos.ProcesarPedidos.PedidoEntregado;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Stack;
import javax.swing.DefaultListModel;

/**
 *
 * @author IT
 */
public class HistorialPedidosCompletados extends javax.swing.JFrame {
private Stack<PedidoEntregado> pedidosEntregados;
    /**
     * Creates new form HistorialPedidosCompletados
     */
    public HistorialPedidosCompletados(Stack<PedidoEntregado> pedidosEntregados) {
        initComponents();
        this.setVisible(true);
        this.pedidosEntregados = pedidosEntregados;  
        cargarHistorialPedidos(pedidosEntregados);
    }
    
    
    //////////////////////////////////////////////////////////////////////////////////////////agrega el listado al jlist
    private void cargarHistorialPedidos(Stack<PedidoEntregado> pedidosEntregados) {
    // Convertir la pila a una lista temporal
    List<PedidoEntregado> listaTemporal = new ArrayList<>(pedidosEntregados);

    // Ordenar por fecha de entrega (de más antiguo a más reciente)
    listaTemporal.sort(Comparator.comparing(PedidoEntregado::getFechaHoraEntregaComoLocalDateTime));

    // Crear el modelo para el JList
    DefaultListModel<String> modelo = new DefaultListModel<>();
    double totalMonto = 0.0;

    for (PedidoEntregado pedido : listaTemporal) {
        modelo.addElement(pedido.toString());

        // Acceder al campo 'total' desde la clase padre Pedido
        try {
            Field field = pedido.getClass().getSuperclass().getDeclaredField("total");
            field.setAccessible(true);
            Object valor = field.get(pedido);
            if (valor instanceof Number) {
                totalMonto += ((Number) valor).doubleValue();
            }
        } catch (NoSuchFieldException | IllegalAccessException e) {
            e.printStackTrace();
        }
    }

    // Asignar el modelo al JList
    JLIST_listado.setModel(modelo);
}

     
/////////////////////////////////////////////////////////////////////////////////////////////////BUSCAR PEDIDO 
    
    
private void buscarPedidoPorId() {
    String idBuscado = TXT_idbuscar.getText().trim();
    DefaultListModel<String> modeloLista = new DefaultListModel<>();

    for (PedidoEntregado pedido : pedidosEntregados) {
        if (pedido.toString().contains(idBuscado)) {
            modeloLista.addElement(pedido.toString());
        }
    }

    if (modeloLista.isEmpty()) {
        modeloLista.addElement("No se encontró ningún pedido con el ID: " + idBuscado);
    }

    JLIST_listado2.setModel(modeloLista);
}

  ////////////////////////////////////////////////////////////////////////////////////////////////  LIMPIAR PANTALLA
    

  private void limpiarPantalla() {
    // Limpiar el campo de texto
    TXT_idbuscar.setText("");

    // Limpiar el JList
    DefaultListModel<String> modeloVacio = new DefaultListModel<>();
    JLIST_listado2.setModel(modeloVacio);
    TXT_idbuscar.requestFocus();
}
  
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JLIST_listado = new javax.swing.JList<>();
        J_listado = new javax.swing.JLabel();
        J_buscar = new javax.swing.JLabel();
        TXT_idbuscar = new javax.swing.JTextField();
        B_buscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JLIST_listado2 = new javax.swing.JList<>();
        B_salir = new javax.swing.JButton();
        B_limpiarpantalla = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Cafeteria Elizabeth");
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel2.setText("Historial Pedidos Completados");

        JLIST_listado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(JLIST_listado);

        J_listado.setText("Listado de Pedidos Completados");
        J_listado.setBorder(new javax.swing.border.MatteBorder(null));

        J_buscar.setText("Buscar pedido por Id");
        J_buscar.setBorder(new javax.swing.border.MatteBorder(null));

        B_buscar.setText("Buscar");
        B_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_buscarMouseClicked(evt);
            }
        });

        jScrollPane2.setViewportView(JLIST_listado2);

        B_salir.setText("Salir");
        B_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_salirMouseClicked(evt);
            }
        });

        B_limpiarpantalla.setText("Limpiar Pantalla");
        B_limpiarpantalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_limpiarpantallaMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Descripcion");
        jLabel3.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(J_listado)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(276, 276, 276))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(J_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(B_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TXT_idbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(B_limpiarpantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2)
                                    .addComponent(B_salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(J_listado)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(J_buscar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_idbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_limpiarpantalla))
                        .addGap(18, 18, 18)
                        .addComponent(B_buscar)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_salirMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_B_salirMouseClicked

    private void B_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_buscarMouseClicked
        // TODO add your handling code here:
        buscarPedidoPorId();
    }//GEN-LAST:event_B_buscarMouseClicked

    private void B_limpiarpantallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_limpiarpantallaMouseClicked
        // TODO add your handling code here:
        limpiarPantalla();
    }//GEN-LAST:event_B_limpiarpantallaMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_buscar;
    private javax.swing.JButton B_limpiarpantalla;
    private javax.swing.JButton B_salir;
    private javax.swing.JList<String> JLIST_listado;
    private javax.swing.JList<String> JLIST_listado2;
    private javax.swing.JLabel J_buscar;
    private javax.swing.JLabel J_listado;
    private javax.swing.JTextField TXT_idbuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
