/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;
import Nuevo_Pedido.Menu_Nuevo_Pedido;
import ProcesarPedidos.ProcesarPedidos;
import HistorialPedidosCompletados.HistorialPedidosCompletados;
import ReporteFinanciero.ReporteFinanciero;

/**
 *
 * @author IT
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
         this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        M_siguientepedido = new javax.swing.JMenu();
        M_nuevopedido = new javax.swing.JMenuItem();
        M_opcion2 = new javax.swing.JMenuItem();
        M_pedidospendientes = new javax.swing.JMenuItem();
        M_reportefinanciero = new javax.swing.JMenuItem();
        M_guardarhistorial = new javax.swing.JMenuItem();
        M_cargarpedido = new javax.swing.JMenuItem();
        M_salir = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(600, 250));

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        M_siguientepedido.setText("MENU PRINCIPAL");
        M_siguientepedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        M_nuevopedido.setText("Nuevo Pedido");
        M_nuevopedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        M_nuevopedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_nuevopedidoActionPerformed(evt);
            }
        });
        M_siguientepedido.add(M_nuevopedido);

        M_opcion2.setText("Procesar Pedidos");
        M_opcion2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        M_opcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_opcion2ActionPerformed(evt);
            }
        });
        M_siguientepedido.add(M_opcion2);

        M_pedidospendientes.setText("Historial de Pedidos Completados");
        M_pedidospendientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        M_pedidospendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_pedidospendientesActionPerformed(evt);
            }
        });
        M_siguientepedido.add(M_pedidospendientes);

        M_reportefinanciero.setText("Reporte Financiero");
        M_reportefinanciero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        M_reportefinanciero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_reportefinancieroMouseClicked(evt);
            }
        });
        M_reportefinanciero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_reportefinancieroActionPerformed(evt);
            }
        });
        M_siguientepedido.add(M_reportefinanciero);

        M_guardarhistorial.setText("Guardar Pedido en Archivo");
        M_guardarhistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        M_siguientepedido.add(M_guardarhistorial);

        M_cargarpedido.setText("Cargar Pedido por Archivo");
        M_cargarpedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        M_siguientepedido.add(M_cargarpedido);

        jMenuBar1.add(M_siguientepedido);

        M_salir.setText("SALIR");
        M_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        M_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_salirMouseClicked(evt);
            }
        });
        jMenuBar1.add(M_salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void M_nuevopedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_nuevopedidoActionPerformed
        // TODO add your handling code here:
        Menu_Nuevo_Pedido menupedido = new Menu_Nuevo_Pedido();
    }//GEN-LAST:event_M_nuevopedidoActionPerformed

    private void M_opcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_opcion2ActionPerformed
        // TODO add your handling code here:
        ProcesarPedidos pedidos = new ProcesarPedidos(Menu_Nuevo_Pedido.colaPedidos);
    }//GEN-LAST:event_M_opcion2ActionPerformed

    private void M_pedidospendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_pedidospendientesActionPerformed
        // TODO add your handling code here:
        HistorialPedidosCompletados historial = new HistorialPedidosCompletados(ProcesarPedidos.pedidosEntregados);
    }//GEN-LAST:event_M_pedidospendientesActionPerformed

    private void M_reportefinancieroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_reportefinancieroMouseClicked

    }//GEN-LAST:event_M_reportefinancieroMouseClicked

    private void M_reportefinancieroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_reportefinancieroActionPerformed
        // TODO add your handling code here:
        ReporteFinanciero reportefinanciero = new ReporteFinanciero(ProcesarPedidos.pedidosEntregados);
    }//GEN-LAST:event_M_reportefinancieroActionPerformed

    private void M_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_salirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_M_salirMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem M_cargarpedido;
    private javax.swing.JMenuItem M_guardarhistorial;
    private javax.swing.JMenuItem M_nuevopedido;
    private javax.swing.JMenuItem M_opcion2;
    private javax.swing.JMenuItem M_pedidospendientes;
    private javax.swing.JMenuItem M_reportefinanciero;
    private javax.swing.JMenu M_salir;
    private javax.swing.JMenu M_siguientepedido;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
