/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProcesarPedidos;
import Nuevo_Pedido.Menu_Nuevo_Pedido;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Queue;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author IT
 */
public class ProcesarPedidos extends javax.swing.JFrame {

private Queue<Menu_Nuevo_Pedido.Pedido> colaPedidos;//////cola
public static Stack<PedidoEntregado> pedidosEntregados = new Stack<>();////pila


    /**
     * Creates new form ProcesarPedidos
     */
    public ProcesarPedidos(Queue<Menu_Nuevo_Pedido.Pedido> colaPedidos) {
        initComponents();
        this.setVisible(true);
        this.colaPedidos = colaPedidos; 
        cargarpedidos();
       
    }
    
         
    /////////////////////////////////////////////////////////////////////////////recorrido de la cola para mostrarla en mi list y mostrar el primer ID en el jlabel
private void cargarpedidos() {
    if (colaPedidos == null || colaPedidos.isEmpty()) {
        JTA_listado.setText("No hay pedidos en la cola.");
        J_id.setText(""); // Limpia el JLabel si no hay pedidos
        return;
    }

    // Mostrar el listado de pedidos
    StringBuilder listado = new StringBuilder();
    for (Menu_Nuevo_Pedido.Pedido pedido : colaPedidos) {
        listado.append(pedido.toString())
               .append("\n-----------------------------\n");
    }
    JTA_listado.setText(listado.toString());

    // Mostrar solo el ID del primer pedido en el JLabel
    Menu_Nuevo_Pedido.Pedido primerPedido = colaPedidos.peek();
    if (primerPedido != null) {
        J_id.setText(String.valueOf(primerPedido.getId()));
    } else {
        J_id.setText(""); // Por si acaso peek() devuelve null
    }
}


    ////////////////////////////////////////////////////////////////////////////////////////se captura la fecha y hora en que se esta entregando el pedido


public class PedidoEntregado {
    public Menu_Nuevo_Pedido.Pedido pedido;
    public String fechaHoraEntrega;

    public PedidoEntregado(Menu_Nuevo_Pedido.Pedido pedido, String fechaHoraEntrega) {
        this.pedido = pedido;
        this.fechaHoraEntrega = fechaHoraEntrega;
    }

    public LocalDateTime getFechaHoraEntregaComoLocalDateTime() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        return LocalDateTime.parse(fechaHoraEntrega, formatter);
    }

    @Override
    public String toString() {
        return pedido.toString() + "\nEntregado: " + fechaHoraEntrega;
    }
}

   //////////////////////////////////////////////////////////////////////////////////////////////////// finaliza el pedido, guarda en pilas los pedidos completados   


private void entregado() {
    if (colaPedidos.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay pedidos pendientes.");
        J_id.setText(""); // Limpiar el JLabel
        return;
    }

    // Obtener el primer pedido de la cola sin eliminarlo aún
    Menu_Nuevo_Pedido.Pedido pedido = colaPedidos.peek();

    if (pedido != null) {
        // Eliminar el pedido de la cola
        colaPedidos.poll();

        // Registrar la fecha y hora de entrega
        String fechaHoraEntrega = LocalDateTime.now()
            .format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));

        // Crear objeto entregado y agregarlo a la pila
        PedidoEntregado entregado = new PedidoEntregado(pedido, fechaHoraEntrega);
        pedidosEntregados.push(entregado);

        // Mostrar mensaje de confirmación
        JOptionPane.showMessageDialog(this, "Pedido entregado:\n" + entregado.toString());

        // Actualizar el listado (aquí deberías llamar a tu método que refresca la tabla o lista)
        cargarpedidos();

        // Mostrar el siguiente ID en el JLabel (si hay más pedidos)
        if (!colaPedidos.isEmpty()) {
            Menu_Nuevo_Pedido.Pedido siguiente = colaPedidos.peek();
            J_id.setText(String.valueOf(siguiente.id));
        } else {
            J_id.setText(""); // No hay más pedidos
        }
    }
}


    /////////////////////////////////////////////////////////////////////////////////////////////////////////


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        J_nombre = new javax.swing.JLabel();
        J_status = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_listado = new javax.swing.JTextArea();
        J_listado = new javax.swing.JLabel();
        B_entregado = new javax.swing.JButton();
        B_salir = new javax.swing.JButton();
        J_id = new javax.swing.JLabel();
        J_numeropedido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 100));

        J_nombre.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        J_nombre.setText("Cafeteria Elizabeth");
        J_nombre.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        J_status.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        J_status.setText("STATUS DE PEDIDOS");

        JTA_listado.setColumns(20);
        JTA_listado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JTA_listado.setRows(5);
        jScrollPane1.setViewportView(JTA_listado);

        J_listado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        J_listado.setText("Listado de Pedidos Pendientes");

        B_entregado.setText("ENTREGADO");
        B_entregado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        B_entregado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_entregadoMouseClicked(evt);
            }
        });

        B_salir.setText("SALIR");
        B_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_salirMouseClicked(evt);
            }
        });

        J_id.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        J_id.setText("ID");

        J_numeropedido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        J_numeropedido.setText("PEDIDO #");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(J_listado, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(595, 595, 595))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(J_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(J_status, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(J_id, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(J_numeropedido, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(B_entregado, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(B_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(J_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J_status, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(J_listado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(J_numeropedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(J_id, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(B_entregado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addComponent(B_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_salirMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_B_salirMouseClicked

    private void B_entregadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_entregadoMouseClicked
        // TODO add your handling code here:
       entregado();
    }//GEN-LAST:event_B_entregadoMouseClicked

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_entregado;
    private javax.swing.JButton B_salir;
    private javax.swing.JTextArea JTA_listado;
    private javax.swing.JLabel J_id;
    private javax.swing.JLabel J_listado;
    private javax.swing.JLabel J_nombre;
    private javax.swing.JLabel J_numeropedido;
    private javax.swing.JLabel J_status;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
